//go:build tinygo.wasm

// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin 0.7.0
// 	protoc               v3.21.12
// source: plugins.proto

package proto

import (
	context "context"
	wasm "github.com/knqyf263/go-plugin/wasm"
)

const HelperFunctionPluginAPIVersion = 1

//export helper_function_api_version
func _helper_function_api_version() uint64 {
	return HelperFunctionPluginAPIVersion
}

var helperFunction HelperFunction

func RegisterHelperFunction(p HelperFunction) {
	helperFunction = p
}

//export helper_function_info
func _helper_function_info(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(Empty)
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := helperFunction.Info(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}

//export helper_function_execute
func _helper_function_execute(ptr, size uint32) uint64 {
	b := wasm.PtrToByte(ptr, size)
	req := new(HelperFunctionRequest)
	if err := req.UnmarshalVT(b); err != nil {
		return 0
	}
	response, err := helperFunction.Execute(context.Background(), req)
	if err != nil {
		ptr, size = wasm.ByteToPtr([]byte(err.Error()))
		return (uint64(ptr) << uint64(32)) | uint64(size) |
			// Indicate that this is the error string by setting the 32-th bit, assuming that
			// no data exceeds 31-bit size (2 GiB).
			(1 << 31)
	}

	b, err = response.MarshalVT()
	if err != nil {
		return 0
	}
	ptr, size = wasm.ByteToPtr(b)
	return (uint64(ptr) << uint64(32)) | uint64(size)
}
